# Generated by Django 4.1.7 on 2023-03-03 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BNotePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_publish', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('title', models.CharField(max_length=50)),
                ('article', models.CharField(max_length=200)),
                ('start_task', models.DateField(verbose_name='начало')),
                ('fin_task', models.DateField(verbose_name='окончание')),
                ('user_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
