# Generated by Django 4.1.7 on 2023-03-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_bnotepost_data_publish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bnotepost',
            name='start_task',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='начало'),
        ),
    ]
