# Generated by Django 4.1.7 on 2023-03-06 11:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_bnotepost_start_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bnotepost',
            name='start_task',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='начало'),
        ),
        migrations.AlterField(
            model_name='bnotepost',
            name='user_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
