# Generated by Django 4.1.7 on 2023-03-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_bnotepost_start_task_alter_bnotepost_user_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bnotepost',
            name='start_task',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='начало'),
        ),
    ]
