# Generated by Django 4.1.7 on 2023-03-06 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_bnotepost_start_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bnotepost',
            name='start_task',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='начало'),
        ),
    ]
