# Generated by Django 4.1.7 on 2023-03-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_bnotepost_start_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bnotepost',
            name='start_task',
            field=models.DateField(auto_now=True, null=True, verbose_name='начало'),
        ),
    ]
