# Generated by Django 4.1.7 on 2023-03-06 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_bnotepost_start_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bnotepost',
            name='fin_task',
        ),
        migrations.RemoveField(
            model_name='bnotepost',
            name='start_task',
        ),
    ]
