# Generated by Django 4.1.7 on 2023-03-07 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_bnotepost_fin_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bnotepost',
            name='user_post',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
