# Generated by Django 4.1.7 on 2023-03-10 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_bnotepost_user_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bnotepost',
            name='user_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
